[project]
name = "openai-mcp-example"
version = "0.1.2"
description = "OpenAI MCP example"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai>=1.93.0",
    "pydantic-settings>=2.10.1",
]
