# test.yml

name: test

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
      - uses: actions/setup-python@v5
        with:
          python-version-file: .python-version
      - uses: ezhuk/setup-mosquitto@v11
        with:
          version: 'latest'
      - run: |
          uv sync
          uv run ruff format src
          uv run ruff check src
          uv run pytest
      - run: |
          docker stop mosquitto
          docker rm mosquitto
